
dist: bionic
language: cpp

branches:
  only:
    - master

addons:
  apt:
    packages:
      - qtbase5-dev

notifications:
    on_failure: never
    on_success: never

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
