
version: 1.0.{build}

branches:
  only:
    - master
    - appveyor

configuration:
    - Release
    - Debug

platform:
    - x64

image: Visual Studio 2019

cache:
    - c:\projects\googletest   -> appveyor.bat

before_build:
    - call appveyor.bat

build:
  project: build/OpenLibrary.sln
  parallel: true
  verbosity: minimal
