
#rules for finding OpenLibrary
#based on http://www.vtk.org/Wiki/CMake:How_To_Find_Libraries
#and on FindQt4.cmake for Mageia Linux (components part)

if(OpenLibrary_FIND_COMPONENTS)

    foreach(component ${OpenLibrary_FIND_COMPONENTS})
        STRING(TOUPPER ${component} comp_name)
        
        #try to load component's data
        include(autogenerated/partial/${component})
        
    endforeach(component ${OpenLibrary_FIND_COMPONENTS})

endif(OpenLibrary_FIND_COMPONENTS)

set ( HTMLPARSER_LIBRARIES htmlParser ) 
set ( MATH_LIBRARIES math ) 
set ( QTEXT_LIBRARIES QtExt ) 
set ( UTILS_LIBRARIES utils ) 
